version: "3" #版本号
services:
  eureka-server: #服务名称（不是容器名）
    image: "ascdc/jdk8"  #使用的镜像
    ports:
      - "8802:8802"  #暴露的端口信息和docker run -d -p 80:80 一样
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: eureka-server #容器名称
    #挂载文件ps:如果是挂载文件必须在容器中也指定名称，推荐是挂载文件夹，下面只是做个文件挂载的案例也可以
    #挂载文件夹/root/compose_test/jdk/:/data
    volumes:
      - /opt/app/eureka-server/eureka-server-0.0.1-SNAPSHOT.jar:/app.jar
      - /opt/app/eureka-server/auto-code:/script/
    entrypoint: java -Xms128m -Xmx128m -Dspring.profiles.active=prod -Djava.security.egd=file:/dev/./urandom -jar /app.jar #启动容器后执行的命令

    networks:
      wdk:
        ipv4_address: 192.168.1.101
networks:
  wdk:
    external: true