version: '3'
services:
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://192.168.1.14:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
    networks:
      wdk:
        ipv4_address: 192.168.1.15
networks:
  wdk:
    external: true