version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234 #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/db:/var/lib/mysql #数据文件挂载
      - ./mysql/data/conf:/etc/mysql/conf.d #配置文件挂载
      - ./mysql/log:/var/log/mysql #日志文件挂载
    networks:
      wdk:
        ipv4_address: 192.168.1.10
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data #数据文件挂载
    ports:
      - 6379:6379
    networks:
      wdk:
        ipv4_address: 192.168.1.11
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - ./nginx/html:/usr/share/nginx/html #静态资源根目录挂载
      - ./nginx/log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80

    networks:
      wdk:
        ipv4_address: 192.168.1.12
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq #数据文件挂载
      - ./rabbitmq/log:/var/log/rabbitmq #日志文件挂载
    ports:
      - 5672:5672
      - 15672:15672

    networks:
      wdk:
        ipv4_address: 192.168.1.13
  elasticsearch:
    image: elasticsearch:6.4.0
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200

    networks:
      wdk:
        ipv4_address: 192.168.1.14
  kibana:
    image: kibana:6.4.0
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://elasticsearch:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601

    networks:
      wdk:
        ipv4_address: 192.168.1.15
  mongo:
    image: mongo:3.2
    container_name: mongo
    volumes:
      - ./mongo/db:/data/db #数据文件挂载
    ports:
      - 27017:27017

    networks:
      wdk:
        ipv4_address: 192.168.1.18

networks:
  wdk:
    external: true