version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    container_name: mall-admin
    ports:
      - 8080:8080


    networks:
      wdk:
        ipv4_address: 192.168.1.103
  mall-search:
    image: mall/mall-search:1.0-SNAPSHOT
    container_name: mall-search
    ports:
      - 8081:8081



    networks:
      wdk:
        ipv4_address: 192.168.1.102
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    container_name: mall-portal
    ports:
      - 8085:8085

    networks:
      wdk:
        ipv4_address: 192.168.1.101

networks:
  wdk:
    external: true