version: '2'
services:
  dokuwiki:
    build: .
    image: shuosc/dokuwiki:latest
    ports:
      - 8004:80
    environment:
      - DIR=wiki
    volumes:
      - ./data:/opt/data


    networks:
      wdk:
        ipv4_address: 192.168.1.201

networks:
  wdk:
    external: true