version: '2'
services:
  elasticjob-mesos-master:
    image: mesosphere/mesos-master:1.6.0-rc1
    restart: always
    container_name: elasticjob-mesos-master
    ports:
      - "5050:5050"
    environment:
      MESOS_ZK: zk://192.168.1.2:2181/mesos
      MESOS_PORT: 5050
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_QUORUM: 1
      MESOS_REGISTRY: in_memory
      MESOS_WORK_DIR: /var/lib/mesos


    networks:
      wdk:
        ipv4_address: 192.168.1.5

  elasticjob-mesos-agent:
    image: mesosphere/mesos-agent:1.6.0-rc1
    restart: always
    container_name: elasticjob-mesos-agent
    ports:
      - "5051:5051"

    volumes:
      - ./log/mesos:/var/log/mesos
      - ./tmp/mesos:/var/tmp/mesos
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /usr/local/bin/docker:/usr/local/bin/docker

    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://192.168.1.2:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"


    networks:
      wdk:
        ipv4_address: 192.168.1.6


networks:
  wdk:
    external: true