version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - ./html:/usr/share/nginx/html #静态资源根目录挂载
      - ./log:/var/log/nginx #日志文件挂载
    ports:
      - 80:80
    networks:
      wdk:
        ipv4_address: 192.168.1.10
networks:
  wdk:
    external: true