version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234 #设置root帐号密码
    volumes:
      - ./data:/var/lib/mysql #数据文件挂载
      - ./conf:/etc/mysql/conf.d #配置文件挂载
      - ./log:/var/log/mysql #日志文件挂载
    networks:
      wdk:
        ipv4_address: 192.168.1.12
networks:
  wdk:
    external: true