
version: "2" #版本号
services:
  wdk-code-general-core: #服务名称（不是容器名）
    image: "ascdc/jdk8"  #使用的镜像
    ports:
      - "8806:8806"  #暴露的端口信息和docker run -d -p 80:80 一样
    restart: "always" #重启策略，能够使服务保持始终运行，生产环境推荐使用
    container_name: wdk-code-general-core #容器名称
    #挂载文件ps:如果是挂载文件必须在容器中也指定名称，推荐是挂载文件夹，下面只是做个文件挂载的案例也可以
    #挂载文件夹/root/compose_test/jdk/:/data
    volumes:
      - /opt/app/wdk-code-general/wdk-code-general-server-0.0.1-SNAPSHOT.jar:/app.jar
      - /opt/app/wdk-code-general/auto-code:/opt/auto-code/
      - /opt/app/wdk-code-general/file:/script/
      - /opt/app/wdk-code-general/shell:/shell/
    entrypoint: java -Xms128m -Xmx128m -Dspring.profiles.active=prod -Djava.security.egd=file:/dev/./urandom -jar /app.jar #启动容器后执行的命令

    networks:
      wdk:
        ipv4_address: 192.168.1.103
networks:
  wdk:
    external: true