version: '2'
services:
  postgres:
    image: postgres:9.5.6-alpine
    container_name: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

    networks:
      wdk:
        ipv4_address: 192.168.1.17


networks:
  wdk:
    external: true
